export default [
    {
        type: 'DOC',
        title: '知识体系',
        uuid: 'wjPAZVmr-ghJ8CY1',
        url: 'vtyt8b',
        parent_uuid: '',
        doc_id: 30095627,
        level: 0,
        id: 30095627,
        open_window: 1,
        visible: 1,
        sibling_uuid: '-lnRetcnD89N9Xmr'
    },
    {
        type: 'TITLE',
        title: 'Html&Css',
        uuid: '-lnRetcnD89N9Xmr',
        url: '',
        parent_uuid: '',
        doc_id: '',
        level: 0,
        id: '',
        open_window: 1,
        visible: 1,
        prev_uuid: 'wjPAZVmr-ghJ8CY1',
        child_uuid: 'V4qwUAzA3FNXFr4s',
        sibling_uuid: '9WQ4yML_kUz0C-8J'
    },
    {
        type: 'DOC',
        title: '小技巧',
        uuid: 'V4qwUAzA3FNXFr4s',
        url: 'hy2hsm',
        parent_uuid: '-lnRetcnD89N9Xmr',
        doc_id: 73211443,
        level: 1,
        id: 73211443,
        open_window: 0,
        visible: 1,
        prev_uuid: '-lnRetcnD89N9Xmr',
        sibling_uuid: 'I5MoRsLdyrNkyojl'
    },
    {
        type: 'DOC',
        title: '盒模型',
        uuid: 'I5MoRsLdyrNkyojl',
        url: 'pgcdv6',
        parent_uuid: '-lnRetcnD89N9Xmr',
        doc_id: 72677007,
        level: 1,
        id: 72677007,
        open_window: 0,
        visible: 1,
        prev_uuid: 'V4qwUAzA3FNXFr4s',
        sibling_uuid: 'r13sjzVgGMS32L5E'
    },
    {
        type: 'DOC',
        title: 'BEM',
        uuid: 'r13sjzVgGMS32L5E',
        url: 'omgrix',
        parent_uuid: '-lnRetcnD89N9Xmr',
        doc_id: 52861839,
        level: 1,
        id: 52861839,
        open_window: 0,
        visible: 1,
        prev_uuid: 'I5MoRsLdyrNkyojl',
        sibling_uuid: 'pcYwe5VsipquELEv'
    },
    {
        type: 'DOC',
        title: 'Scss',
        uuid: 'pcYwe5VsipquELEv',
        url: 'oec37h',
        parent_uuid: '-lnRetcnD89N9Xmr',
        doc_id: 33088332,
        level: 1,
        id: 33088332,
        open_window: 1,
        visible: 1,
        prev_uuid: 'r13sjzVgGMS32L5E',
        sibling_uuid: 'sTIUUcsigO4KE-ll'
    },
    {
        type: 'DOC',
        title: '面试题',
        uuid: 'sTIUUcsigO4KE-ll',
        url: 'qa8q8y',
        parent_uuid: '-lnRetcnD89N9Xmr',
        doc_id: 76044185,
        level: 1,
        id: 76044185,
        open_window: 0,
        visible: 1,
        prev_uuid: 'pcYwe5VsipquELEv'
    },
    {
        type: 'TITLE',
        title: 'JavaScript',
        uuid: '9WQ4yML_kUz0C-8J',
        url: '',
        parent_uuid: '',
        doc_id: '',
        level: 0,
        id: '',
        open_window: 1,
        visible: 1,
        prev_uuid: '-lnRetcnD89N9Xmr',
        child_uuid: 'pC9zKXATLpn_wIq_',
        sibling_uuid: '-X8aUjsq0ghjEIkw'
    },
    {
        type: 'DOC',
        title: '模块系统概述',
        uuid: 'pC9zKXATLpn_wIq_',
        url: 'akm5co',
        parent_uuid: '9WQ4yML_kUz0C-8J',
        doc_id: 49447834,
        level: 1,
        id: 49447834,
        open_window: 0,
        visible: 1,
        prev_uuid: '9WQ4yML_kUz0C-8J',
        sibling_uuid: 'tCFT4WdjN1tsD7BK'
    },
    {
        type: 'DOC',
        title: 'Dom&Bom',
        uuid: 'tCFT4WdjN1tsD7BK',
        url: 'zll96u',
        parent_uuid: '9WQ4yML_kUz0C-8J',
        doc_id: 71583090,
        level: 1,
        id: 71583090,
        open_window: 0,
        visible: 1,
        prev_uuid: 'pC9zKXATLpn_wIq_',
        sibling_uuid: 'rZZ9fHEdWak1AVw0'
    },
    {
        type: 'DOC',
        title: '数据类型',
        uuid: 'rZZ9fHEdWak1AVw0',
        url: 'ear0u5',
        parent_uuid: '9WQ4yML_kUz0C-8J',
        doc_id: 45627157,
        level: 1,
        id: 45627157,
        open_window: 1,
        visible: 1,
        prev_uuid: 'tCFT4WdjN1tsD7BK',
        sibling_uuid: 'OsmMBoa-KoxdzdK_'
    },
    {
        type: 'DOC',
        title: '深拷贝',
        uuid: 'OsmMBoa-KoxdzdK_',
        url: 'hx6lx1',
        parent_uuid: '9WQ4yML_kUz0C-8J',
        doc_id: 33154445,
        level: 1,
        id: 33154445,
        open_window: 1,
        visible: 1,
        prev_uuid: 'rZZ9fHEdWak1AVw0',
        sibling_uuid: 'K7VsreqrBHjnrTjL'
    },
    {
        type: 'DOC',
        title: '原型和原型链',
        uuid: 'K7VsreqrBHjnrTjL',
        url: 'cg8vl1',
        parent_uuid: '9WQ4yML_kUz0C-8J',
        doc_id: 33154400,
        level: 1,
        id: 33154400,
        open_window: 1,
        visible: 1,
        prev_uuid: 'OsmMBoa-KoxdzdK_',
        sibling_uuid: 'CP_9K0kzRL3ud5UY'
    }
]
